name: Build and upload artifact

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
          run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Brick
          path: build/libs/BrickPermissions-*.jar
          if-no-files-found: 'error'